import type { Industry, IndustryId } from './types'

export const INDUSTRIES: Record<IndustryId, Industry> = {
  saas: {
    id: 'saas',
    name: 'B2B SaaS',
    blurb: '企业工具。客单价高，销售周期长，获客贵。',
    baseCac: 800,
    visitToSignup: 0.02,
    signupToPaid: 0.012,
    monthlyChurn: 0.08,
    avgPrice: 199,
    buildMonths: 3,
    salaryPerHead: 18000,
    difficulty: '硬核',
  },
  consumer: {
    id: 'consumer',
    name: '消费级 App',
    blurb: 'C 端产品。流量贵、留存难、广告战残酷。',
    baseCac: 35,
    visitToSignup: 0.025,
    signupToPaid: 0.008,
    monthlyChurn: 0.18,
    avgPrice: 18,
    buildMonths: 2,
    salaryPerHead: 16000,
    difficulty: '极难',
  },
  content: {
    id: 'content',
    name: '内容 / 社群',
    blurb: '知识付费或社群。信任慢，转化靠口碑。',
    baseCac: 60,
    visitToSignup: 0.03,
    signupToPaid: 0.02,
    monthlyChurn: 0.12,
    avgPrice: 49,
    buildMonths: 1,
    salaryPerHead: 12000,
    difficulty: '中等',
  },
  hardware: {
    id: 'hardware',
    name: '硬件 / 供应链',
    blurb: '库存、模具、良率。现金流杀手。',
    baseCac: 120,
    visitToSignup: 0.015,
    signupToPaid: 0.04,
    monthlyChurn: 0.05,
    avgPrice: 399,
    buildMonths: 5,
    salaryPerHead: 15000,
    difficulty: '极难',
  },
  local: {
    id: 'local',
    name: '本地生活',
    blurb: '线下门店或到家服务。租金与人力是主旋律。',
    baseCac: 45,
    visitToSignup: 0.04,
    signupToPaid: 0.06,
    monthlyChurn: 0.1,
    avgPrice: 68,
    buildMonths: 2,
    salaryPerHead: 9000,
    difficulty: '困难',
  },
  ai_tool: {
    id: 'ai_tool',
    name: 'AI 工具',
    blurb: '赛道拥挤。模型成本、同质化、用户尝鲜即走。',
    baseCac: 50,
    visitToSignup: 0.028,
    signupToPaid: 0.01,
    monthlyChurn: 0.22,
    avgPrice: 29,
    buildMonths: 2,
    salaryPerHead: 22000,
    difficulty: '极难',
  },
}

export const CAPITAL_PRESETS = [
  { label: '¥5 万 · 副业试水', value: 50000 },
  { label: '¥20 万 · 个人积蓄', value: 200000 },
  { label: '¥80 万 · 天使前', value: 800000 },
  { label: '¥300 万 · 种子轮', value: 3000000 },
]
